#!/bin/sh

set -e
r10k_dir=/etc/puppetlabs/r10k
mkdir -p $r10k_dir
if [[ -f "${r10k_dir}/r10k.yaml" ]]; then
  [ -n $DEBUG ] && echo "Using provided R10k configuration"
else
  if [ -z $GIT_REMOTE ]; then
    echo 'Error: $GIT_REMOTE is undefined'
    exit 1
  fi

  [ -n $DEBUG ] && echo "Configuring R10k to use $GIT_REMOTE"
  cat > $r10k_dir/r10k.yaml <<-EOF
:cachedir: /var/cache/r10k

:sources:
  :my-org:
    remote: $GIT_REMOTE
    basedir: /etc/puppetlabs/code/environments
EOF
fi
